2022-10-04 19:27:45,156 [main] ERROR com.i2i.recruitment.dao.impl.EmployeeDaoImpl 46- Could not create connection to database server. Attempted reconnect 3 times. Giving up.s
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_341]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-jar.jar:5.1.46]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_341]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-jar.jar:5.1.46]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_341]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_341]
	at com.i2i.recruitment.connections.DatabaseConnection.<init>(DatabaseConnection.java:38) ~[RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.connections.DatabaseConnection.getConnection(DatabaseConnection.java:50) ~[RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.dao.impl.EmployeeDaoImpl.getEmployeeById(EmployeeDaoImpl.java:85) [RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.service.impl.EmployeeServiceImpl.getEmployeeById(EmployeeServiceImpl.java:44) [RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.controller.EmployeeController.getEmployeeById(EmployeeController.java:169) [RecruitmentManagementSystem/:?]
	at RecruitmentManagementSystem.getEmployeeById(RecruitmentManagementSystem.java:1171) [RecruitmentManagementSystem/:?]
	at RecruitmentManagementSystem.viewEmployeeMenu(RecruitmentManagementSystem.java:1114) [RecruitmentManagementSystem/:?]
	at RecruitmentManagementSystem.viewWelcomeMenu(RecruitmentManagementSystem.java:80) [RecruitmentManagementSystem/:?]
	at RecruitmentManagementSystem.recruiteOperation(RecruitmentManagementSystem.java:62) [RecruitmentManagementSystem/:?]
	at RecruitmentManagementSystem.main(RecruitmentManagementSystem.java:54) [RecruitmentManagementSystem/:?]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_341]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:878) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:874) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1777) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037) ~[mysql-connector-jar.jar:5.1.46]
	... 22 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_341]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1775) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037) ~[mysql-connector-jar.jar:5.1.46]
	... 22 more
2022-10-04 19:27:45,179 [main] ERROR com.i2i.recruitment.dao.impl.EmployeeDaoImpl 46- Employee ID not found exception...s
com.i2i.recruitment.exception.CustomException: Employee ID not found exception...
	at com.i2i.recruitment.dao.impl.EmployeeDaoImpl.getEmployeeById(EmployeeDaoImpl.java:107) ~[RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.service.impl.EmployeeServiceImpl.getEmployeeById(EmployeeServiceImpl.java:44) ~[RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.controller.EmployeeController.getEmployeeById(EmployeeController.java:169) ~[RecruitmentManagementSystem/:?]
	at RecruitmentManagementSystem.getEmployeeById(RecruitmentManagementSystem.java:1171) [RecruitmentManagementSystem/:?]
	at RecruitmentManagementSystem.viewEmployeeMenu(RecruitmentManagementSystem.java:1114) [RecruitmentManagementSystem/:?]
	at RecruitmentManagementSystem.viewWelcomeMenu(RecruitmentManagementSystem.java:80) [RecruitmentManagementSystem/:?]
	at RecruitmentManagementSystem.recruiteOperation(RecruitmentManagementSystem.java:62) [RecruitmentManagementSystem/:?]
	at RecruitmentManagementSystem.main(RecruitmentManagementSystem.java:54) [RecruitmentManagementSystem/:?]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_341]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2096) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-jar.jar:5.1.46]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_341]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-jar.jar:5.1.46]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_341]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_341]
	at com.i2i.recruitment.connections.DatabaseConnection.<init>(DatabaseConnection.java:38) ~[RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.connections.DatabaseConnection.getConnection(DatabaseConnection.java:50) ~[RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.dao.impl.EmployeeDaoImpl.getEmployeeById(EmployeeDaoImpl.java:85) ~[RecruitmentManagementSystem/:?]
	... 7 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_341]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:878) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:874) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1777) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-jar.jar:5.1.46]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_341]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-jar.jar:5.1.46]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_341]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_341]
	at com.i2i.recruitment.connections.DatabaseConnection.<init>(DatabaseConnection.java:38) ~[RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.connections.DatabaseConnection.getConnection(DatabaseConnection.java:50) ~[RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.dao.impl.EmployeeDaoImpl.getEmployeeById(EmployeeDaoImpl.java:85) ~[RecruitmentManagementSystem/:?]
	... 7 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_341]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1775) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2021) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-jar.jar:5.1.46]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_341]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[mysql-connector-jar.jar:5.1.46]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-jar.jar:5.1.46]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_341]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_341]
	at com.i2i.recruitment.connections.DatabaseConnection.<init>(DatabaseConnection.java:38) ~[RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.connections.DatabaseConnection.getConnection(DatabaseConnection.java:50) ~[RecruitmentManagementSystem/:?]
	at com.i2i.recruitment.dao.impl.EmployeeDaoImpl.getEmployeeById(EmployeeDaoImpl.java:85) ~[RecruitmentManagementSystem/:?]
	... 7 more
